version: '3.7'
services:
  api:
    container_name: nodejs
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".vscode:/api/.vscode"
    environment:
      PORT: "3000"
      NODE_ENV: "development"
    ports: ["3000:3000"]
    tty: true
    
    